#!/usr/bin/env python3
"""gen_collector_configs.py — Generate sFlow/NetFlow collector configs from device inventory.

Produces pmacct (nfacctd/sfacctd) and softflowd configs plus a Docker Compose
stack for the full flow collection pipeline.

Usage:
  python gen_collector_configs.py --out ./collector_configs
  python gen_collector_configs.py --protocol sflow --port 6343
  python gen_collector_configs.py --protocol netflow --port 9995 --prometheus-port 9514
"""
from __future__ import annotations
import argparse, json, os
from pathlib import Path

INVENTORY_PATH = Path(os.environ.get("DEVICE_INVENTORY", "device_inventory.json"))


def load_inventory() -> list[dict]:
    if INVENTORY_PATH.exists():
        return json.loads(INVENTORY_PATH.read_text())
    return []


def gen_pmacct_nfacctd(port: int, prometheus_port: int) -> str:
    return f"""! nfacctd.conf — NetFlow/IPFIX collector (pmacct)
! Generated by ads-grafana-toolkit gen_collector_configs.py

daemonize: false
pidfile: /var/run/pmacct/nfacctd.pid
logfile: /var/log/pmacct/nfacctd.log

! Listener
nfacctd_port: {port}
nfacctd_ip: 0.0.0.0

! Aggregate by src/dst IP, AS, protocol, port
aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, in_iface, out_iface, peer_src_ip

! Sampling
nfacctd_account_options: true
nfacctd_time_new: true

! Prometheus output
plugins: prometheus[prom1]
prometheus_port[prom1]: {prometheus_port}
prometheus_output[prom1]: gauge
prometheus_refresh_time[prom1]: 60

! Memory tables (pre-aggregation)
imt_path[prom1]: /tmp/nfacctd_prom.pipe
"""


def gen_pmacct_sfacctd(port: int, prometheus_port: int) -> str:
    return f"""! sfacctd.conf — sFlow collector (pmacct)
! Generated by ads-grafana-toolkit gen_collector_configs.py

daemonize: false
sfacctd_port: {port}
sfacctd_ip: 0.0.0.0

aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, in_iface, out_iface

plugins: prometheus[prom1]
prometheus_port[prom1]: {prometheus_port}
prometheus_output[prom1]: gauge
prometheus_refresh_time[prom1]: 60
"""


def gen_softflowd(devices: list[dict], iface: str = "eth0") -> str:
    lines = [f"# softflowd config — export NetFlow v9 from interface {iface}",
             f"# Generated by ads-grafana-toolkit",
             f"",
             f"interface={iface}",
             f"export-version=9",
             f"timeout-general=60",
             f"timeout-tcp=600",
             f"timeout-tcp-rst=30",
             f"timeout-tcp-fin=300",
             f""]
    lines.append("# Collector targets (update host/port per deployment):")
    lines.append("host=127.0.0.1")
    lines.append("port=9995")
    return "\n".join(lines)


def gen_prometheus_scrape(prometheus_port: int) -> str:
    return f"""# Prometheus scrape config for flow collector
# Add to your prometheus.yml scrape_configs:

  - job_name: pmacct_flows
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:{prometheus_port}']
        labels:
          collector: pmacct
"""


def gen_compose(protocol: str, flow_port: int, prometheus_port: int) -> str:
    daemon = "sfacctd" if protocol == "sflow" else "nfacctd"
    cfg_file = f"{daemon}.conf"
    return f"""version: "3.8"
services:
  {daemon}:
    image: pmacct/pmacct:latest
    container_name: {daemon}
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./{cfg_file}:/etc/pmacct/{cfg_file}:ro
      - pmacct-logs:/var/log/pmacct
      - pmacct-run:/var/run/pmacct
    command: {daemon} -f /etc/pmacct/{cfg_file}
    ports:
      - "{flow_port}:{flow_port}/udp"
      - "{prometheus_port}:{prometheus_port}/tcp"

volumes:
  pmacct-logs:
  pmacct-run:
"""


def main() -> None:
    p = argparse.ArgumentParser(description="Generate sFlow/NetFlow collector configs")
    p.add_argument("--out", default="collector_configs")
    p.add_argument("--protocol", choices=["netflow", "sflow", "both"], default="both")
    p.add_argument("--netflow-port", type=int, default=9995, dest="nf_port")
    p.add_argument("--sflow-port", type=int, default=6343, dest="sf_port")
    p.add_argument("--prometheus-port", type=int, default=9514, dest="prom_port")
    p.add_argument("--interface", default="eth0")
    args = p.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    devices = load_inventory()

    files_written = []

    if args.protocol in ("netflow", "both"):
        (out / "nfacctd.conf").write_text(gen_pmacct_nfacctd(args.nf_port, args.prom_port))
        files_written.append("nfacctd.conf")
        (out / "docker-compose.nfacctd.yml").write_text(
            gen_compose("netflow", args.nf_port, args.prom_port))
        files_written.append("docker-compose.nfacctd.yml")

    if args.protocol in ("sflow", "both"):
        (out / "sfacctd.conf").write_text(gen_pmacct_sfacctd(args.sf_port, args.prom_port + 1))
        files_written.append("sfacctd.conf")
        (out / "docker-compose.sfacctd.yml").write_text(
            gen_compose("sflow", args.sf_port, args.prom_port + 1))
        files_written.append("docker-compose.sfacctd.yml")

    (out / "softflowd.conf").write_text(gen_softflowd(devices, args.interface))
    files_written.append("softflowd.conf")

    (out / "prometheus_flow_scrape.yml").write_text(gen_prometheus_scrape(args.prom_port))
    files_written.append("prometheus_flow_scrape.yml")

    print(f"Written to {out}/:")
    for f in files_written:
        print(f"  {f}")
    if devices:
        print(f"\n{len(devices)} devices in inventory — configure them to export flows to this collector.")
    else:
        print("\nNo device inventory found — add devices with setup_network_devices.py.")

if __name__ == "__main__": main()
