"""Pre-built alert rules for AWS, GCP, and Azure cloud resources."""
from ads_grafana_toolkit.alerts.rules import AlertRule, AlertGroup

CLOUD_ALERT_GROUPS = [
    AlertGroup(
        name="AWS Alerts",
        folder="Cloud Alerts",
        interval="5m",
        rules=[
            AlertRule(uid="aws-ec2-cpu-high", title="EC2 CPU > 85%",
                expr='{"metricName":"CPUUtilization","namespace":"AWS/EC2","statistics":["Average"]}',
                datasource_uid="cloudwatch",
                for_duration="10m", severity="warning", team="cloud-ops",
                summary="High CPU on EC2 {{ $labels.InstanceId }}",
                description="{{ $labels.InstanceId }} CPU at {{ $value | printf \"%.1f\" }}%.",
                threshold_value=85, threshold_type="gt"),
            AlertRule(uid="aws-rds-storage-low", title="RDS Free Storage < 10GB",
                expr='{"metricName":"FreeStorageSpace","namespace":"AWS/RDS","statistics":["Average"]}',
                datasource_uid="cloudwatch",
                for_duration="15m", severity="warning", team="cloud-ops",
                summary="Low storage on RDS {{ $labels.DBInstanceIdentifier }}",
                description="{{ $labels.DBInstanceIdentifier }} has {{ $value | printf \"%.0f\" }} bytes free.",
                threshold_value=10737418240, threshold_type="lt"),
            AlertRule(uid="aws-lambda-errors", title="Lambda Error Rate > 5%",
                expr='{"metricName":"Errors","namespace":"AWS/Lambda","statistics":["Sum"]}',
                datasource_uid="cloudwatch",
                for_duration="5m", severity="warning", team="cloud-ops",
                summary="Lambda errors on {{ $labels.FunctionName }}",
                description="{{ $labels.FunctionName }} has elevated error rate.",
                threshold_value=0, threshold_type="gt"),
            AlertRule(uid="aws-dx-down", title="Direct Connect Down",
                expr='{"metricName":"ConnectionState","namespace":"AWS/DX","statistics":["Minimum"]}',
                datasource_uid="cloudwatch",
                for_duration="2m", severity="critical", team="backbone-noc",
                summary="Direct Connect {{ $labels.ConnectionId }} is down",
                description="Direct Connect connection {{ $labels.ConnectionId }} state is 0 (down).",
                threshold_value=1, threshold_type="lt", no_data_state="Alerting"),
        ],
    ),
    AlertGroup(
        name="GCP Alerts",
        folder="Cloud Alerts",
        interval="5m",
        rules=[
            AlertRule(uid="gcp-gce-cpu-high", title="GCE Instance CPU > 85%",
                expr='{"metricType":"compute.googleapis.com/instance/cpu/utilization"}',
                datasource_uid="stackdriver",
                for_duration="10m", severity="warning", team="cloud-ops",
                summary="High CPU on GCE {{ $labels.instance_name }}",
                threshold_value=0.85, threshold_type="gt"),
            AlertRule(uid="gcp-gke-restarts", title="GKE Pod Restart Loop",
                expr='{"metricType":"kubernetes.io/container/restart_count"}',
                datasource_uid="stackdriver",
                for_duration="5m", severity="warning", team="cloud-ops",
                summary="Pod {{ $labels.pod_name }} restarting frequently",
                threshold_value=5, threshold_type="gt"),
        ],
    ),
    AlertGroup(
        name="Azure Alerts",
        folder="Cloud Alerts",
        interval="5m",
        rules=[
            AlertRule(uid="az-vm-cpu-high", title="Azure VM CPU > 85%",
                expr='{"namespace":"Microsoft.Compute/virtualMachines","metricName":"Percentage CPU","aggregation":"Average"}',
                datasource_uid="grafana-azure-monitor-datasource",
                for_duration="10m", severity="warning", team="cloud-ops",
                summary="High CPU on Azure VM {{ $labels.resourceName }}",
                threshold_value=85, threshold_type="gt"),
            AlertRule(uid="az-expressroute-down", title="ExpressRoute Circuit Down",
                expr='{"namespace":"Microsoft.Network/expressRouteCircuits","metricName":"BitsInPerSecond","aggregation":"Average"}',
                datasource_uid="grafana-azure-monitor-datasource",
                for_duration="2m", severity="critical", team="backbone-noc",
                summary="ExpressRoute {{ $labels.resourceName }} appears down",
                threshold_value=0, threshold_type="lt", no_data_state="Alerting"),
        ],
    ),
]
