"""Pre-built ISP alert rules — BGP, interfaces, MPLS, flow collection."""
from ads_grafana_toolkit.alerts.rules import AlertRule, AlertGroup

ISP_ALERT_GROUPS = [
    AlertGroup(
        name="ISP BGP Alerts",
        folder="ISP Alerts",
        interval="1m",
        rules=[
            AlertRule(
                uid="isp-bgp-session-down",
                title="BGP Session Down",
                expr='bgp_session_state{state!="Established"} == 1',
                for_duration="2m",
                severity="critical",
                team="backbone-noc",
                summary="BGP session down on {{ $labels.router }}",
                description="BGP peer {{ $labels.peer_address }} (AS{{ $labels.peer_as }}) on {{ $labels.router }} is not Established. State: {{ $labels.state }}",
                threshold_value=0,
                threshold_type="gt",
                no_data_state="OK",
            ),
            AlertRule(
                uid="isp-bgp-prefix-drop",
                title="BGP Prefix Count Drop > 20%",
                expr='(bgp_prefixes_received - bgp_prefixes_received offset 5m) / bgp_prefixes_received offset 5m * 100 < -20',
                for_duration="5m",
                severity="warning",
                team="backbone-noc",
                summary="BGP prefix count dropped > 20% on {{ $labels.router }}",
                description="Peer AS{{ $labels.peer_as }} on {{ $labels.router }} lost more than 20% of prefixes in the last 5m.",
                threshold_value=-20,
                threshold_type="lt",
                no_data_state="NoData",
            ),
            AlertRule(
                uid="isp-bgp-flapping",
                title="BGP Session Flapping",
                expr='increase(bgp_session_resets_total[15m]) > 3',
                for_duration="1m",
                severity="warning",
                team="backbone-noc",
                summary="BGP session flapping on {{ $labels.router }}",
                description="Peer {{ $labels.peer_address }} on {{ $labels.router }} has reset {{ $value }} times in 15 minutes.",
                threshold_value=3,
                threshold_type="gt",
            ),
        ],
    ),
    AlertGroup(
        name="ISP Interface Alerts",
        folder="ISP Alerts",
        interval="1m",
        rules=[
            AlertRule(
                uid="isp-interface-high-util",
                title="Interface Utilization > 90%",
                expr='rate(ifHCInOctets[5m]) * 8 / ifHighSpeed / 1000000 * 100 > 90',
                for_duration="5m",
                severity="critical",
                team="backbone-noc",
                summary="High utilization on {{ $labels.ifDescr }} @ {{ $labels.instance }}",
                description="{{ $labels.ifDescr }} on {{ $labels.instance }} is at {{ $value | printf \"%.1f\" }}% utilization (inbound).",
                threshold_value=90,
                threshold_type="gt",
            ),
            AlertRule(
                uid="isp-interface-util-warn",
                title="Interface Utilization > 80%",
                expr='rate(ifHCInOctets[5m]) * 8 / ifHighSpeed / 1000000 * 100 > 80',
                for_duration="10m",
                severity="warning",
                team="backbone-noc",
                summary="Elevated utilization on {{ $labels.ifDescr }}",
                description="{{ $labels.ifDescr }} on {{ $labels.instance }} has been above 80% for 10m.",
                threshold_value=80,
                threshold_type="gt",
            ),
            AlertRule(
                uid="isp-interface-errors",
                title="Interface Error Rate Elevated",
                expr='rate(ifInErrors[5m]) + rate(ifOutErrors[5m]) > 10',
                for_duration="5m",
                severity="warning",
                team="backbone-noc",
                summary="Interface errors on {{ $labels.ifDescr }}",
                description="{{ $labels.ifDescr }} on {{ $labels.instance }} is seeing {{ $value | printf \"%.1f\" }} errors/sec.",
                threshold_value=10,
                threshold_type="gt",
            ),
            AlertRule(
                uid="isp-interface-down",
                title="Interface Operationally Down",
                expr='ifOperStatus{ifAdminStatus="1"} == 2',
                for_duration="2m",
                severity="critical",
                team="backbone-noc",
                summary="Interface {{ $labels.ifDescr }} is down on {{ $labels.instance }}",
                description="Admin-up interface {{ $labels.ifDescr }} on {{ $labels.instance }} has gone operationally down.",
                threshold_value=0,
                threshold_type="gt",
                no_data_state="Alerting",
            ),
        ],
    ),
    AlertGroup(
        name="ISP Device Reachability",
        folder="ISP Alerts",
        interval="1m",
        rules=[
            AlertRule(
                uid="isp-snmp-target-down",
                title="SNMP Target Unreachable",
                expr='up{job=~"snmp_.*"} == 0',
                for_duration="3m",
                severity="critical",
                team="backbone-noc",
                summary="SNMP target {{ $labels.instance }} is unreachable",
                description="Prometheus cannot scrape {{ $labels.instance }} via SNMP. Device may be down or SNMP config changed.",
                threshold_value=0,
                threshold_type="gt",
                no_data_state="Alerting",
            ),
            AlertRule(
                uid="isp-device-cpu-high",
                title="Router CPU > 85%",
                expr='cpmCPUTotal5minRev > 85',
                for_duration="10m",
                severity="warning",
                team="backbone-noc",
                summary="High CPU on {{ $labels.instance }}",
                description="{{ $labels.instance }} CPU is at {{ $value }}% for 10+ minutes.",
                threshold_value=85,
                threshold_type="gt",
            ),
        ],
    ),
]
