"""Pre-built alert rules for network hardware — Cisco, Juniper, Palo Alto, Fortinet."""
from ads_grafana_toolkit.alerts.rules import AlertRule, AlertGroup

NETWORK_ALERT_GROUPS = [
    AlertGroup(
        name="Network Device Health",
        folder="Network Alerts",
        interval="2m",
        rules=[
            AlertRule(uid="net-cpu-critical", title="Device CPU Critical (>90%)",
                expr='cpmCPUTotal5minRev > 90 or jnxOperatingCPU > 90',
                for_duration="5m", severity="critical", team="noc",
                summary="CPU critical on {{ $labels.instance }}",
                description="{{ $labels.instance }} CPU at {{ $value }}%.",
                threshold_value=90, threshold_type="gt"),
            AlertRule(uid="net-memory-high", title="Device Memory > 85%",
                expr='ciscoMemoryPoolUsed / (ciscoMemoryPoolUsed + ciscoMemoryPoolFree) * 100 > 85',
                for_duration="10m", severity="warning", team="noc",
                summary="High memory on {{ $labels.instance }}",
                description="{{ $labels.instance }} memory at {{ $value | printf \"%.1f\" }}%.",
                threshold_value=85, threshold_type="gt"),
            AlertRule(uid="net-temperature", title="Device Temperature Critical",
                expr='ciscoEnvMonTemperatureStatusValue > 60 or jnxOperatingTemp > 65',
                for_duration="2m", severity="critical", team="noc",
                summary="High temperature on {{ $labels.instance }}",
                description="{{ $labels.instance }} temperature at {{ $value }}°C.",
                threshold_value=60, threshold_type="gt"),
        ],
    ),
    AlertGroup(
        name="Firewall Alerts",
        folder="Network Alerts",
        interval="1m",
        rules=[
            AlertRule(uid="fw-session-util", title="Firewall Session Table > 90%",
                expr='panSysActiveSessions / panSysMaxSessions * 100 > 90',
                for_duration="5m", severity="critical", team="security-noc",
                summary="Session table near capacity on {{ $labels.instance }}",
                description="{{ $labels.instance }} session table at {{ $value | printf \"%.1f\" }}%.",
                threshold_value=90, threshold_type="gt"),
            AlertRule(uid="fw-ha-failover", title="Firewall HA Failover",
                expr='increase(panSysHAFailoverCount[5m]) > 0',
                for_duration="1m", severity="critical", team="security-noc",
                summary="HA failover detected on {{ $labels.instance }}",
                description="{{ $labels.instance }} had a HA failover event in the last 5 minutes.",
                threshold_value=0, threshold_type="gt"),
            AlertRule(uid="fw-threat-spike", title="Threat Detection Spike",
                expr='rate(panSysThreatTotal[5m]) > 100',
                for_duration="3m", severity="warning", team="security-noc",
                summary="Elevated threat rate on {{ $labels.instance }}",
                description="{{ $labels.instance }} detecting {{ $value | printf \"%.0f\" }} threats/sec.",
                threshold_value=100, threshold_type="gt"),
            AlertRule(uid="fg-session-util", title="FortiGate Session Table > 85%",
                expr='fgSysSesCount / 1000000 * 100 > 85',
                for_duration="5m", severity="warning", team="security-noc",
                summary="FortiGate session table elevated on {{ $labels.instance }}",
                description="{{ $labels.instance }} session count {{ $value | printf \"%.0f\" }}.",
                threshold_value=85, threshold_type="gt"),
        ],
    ),
]
